declare const supabase:any;
const URL='https://ewtgkjcmnwjoqfldrtuw.supabase.co';
const KEY='sb_publishable_ZEAZWO-Q-_rvMsy6krr_nw_JDRmP_kI';
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,(c:string)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'} as any)[c]);

document.head.insertAdjacentHTML('beforeend',`<style>
.series-browser{margin:34px 0 18px;padding:0;background:transparent}.series-browser-head{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:18px}.series-browser-head small{display:block;color:#9b9fa8;font-weight:800;letter-spacing:.12em;margin-bottom:5px}.series-browser-head h2{margin:0;font-size:clamp(1.45rem,3vw,2rem)}.series-browser .episode-count{color:#c8cad0;font-size:.92rem;font-weight:700}.season-tabs{display:flex;gap:10px;overflow-x:auto;padding:2px 0 16px;scrollbar-width:none}.season-tabs::-webkit-scrollbar{display:none}.season-tab{flex:0 0 auto;white-space:nowrap;border:1px solid #343840;background:#181a1f;color:#fff;padding:10px 15px;border-radius:7px;text-decoration:none;font-weight:800;transition:.2s ease}.season-tab:hover{background:#24272d}.season-tab.active{background:#f4f4f4;color:#08090b;border-color:#f4f4f4}.episode-list{display:flex;flex-direction:column;border-top:1px solid #26292f}.episode-btn{width:100%;display:grid;grid-template-columns:52px minmax(0,1fr) auto;align-items:center;gap:16px;border:0;border-bottom:1px solid #26292f;background:transparent;color:#fff;padding:14px 6px;text-align:left;cursor:pointer;transition:background .18s ease}.episode-btn:hover{background:#15171b}.episode-btn.active{background:#1b1d22}.episode-number{font-size:1.1rem;color:#b8bbc2;text-align:center;font-weight:800}.episode-main{min-width:0}.episode-main strong{display:block;font-size:1rem;line-height:1.3;margin-bottom:5px}.episode-main span{display:block;color:#969aa3;font-size:.85rem}.episode-play{width:42px;height:42px;border:1px solid #5a5f68;border-radius:50%;display:grid;place-items:center;font-size:1rem;background:#0e1013}.episode-btn.active .episode-number,.episode-btn.active .episode-main strong{color:#fff}.episode-btn.active .episode-play{background:#fff;color:#08090b;border-color:#fff}.episode-note{margin:14px 0 0;color:#8f939c;font-size:.86rem}@media(max-width:640px){.series-browser{margin-top:26px}.series-browser-head{align-items:flex-end}.series-browser-head h2{font-size:1.35rem}.series-browser .episode-count{font-size:.8rem}.episode-btn{grid-template-columns:36px minmax(0,1fr) 38px;gap:10px;padding:14px 2px}.episode-number{font-size:.95rem}.episode-main strong{font-size:.95rem}.episode-main span{font-size:.78rem}.episode-play{width:36px;height:36px}}
</style>`);

async function boot(){
  while(typeof supabase==='undefined') await new Promise(r=>setTimeout(r,80));
  const slug=new URLSearchParams(location.search).get('slug');if(!slug)return;
  const db=supabase.createClient(URL,KEY);
  const {data:m}=await db.from('movies').select('slug,title,content_type,episode_count,full_video_embed_url').eq('slug',slug).eq('status','published').maybeSingle();
  if(!m||m.content_type!=='series')return;
  for(let i=0;i<80&&!document.querySelector('.movie-hero');i++) await new Promise(r=>setTimeout(r,75));
  const root=document.querySelector<HTMLElement>('#movie-page');if(!root)return;
  const base=String(m.title).replace(/\s+season\s*\d+.*$/i,'').trim();
  const {data:seasons}=await db.from('movies').select('slug,title,episode_count,full_video_embed_url').eq('status','published').eq('content_type','series').ilike('title',`${base}%`);
  const seasonNo=(t:string)=>{const v=String(t).match(/season\s*(\d+)/i);return v?Number(v[1]):1};
  const seasonRows=(seasons||[]).filter((x:any)=>String(x.title).toLowerCase().startsWith(base.toLowerCase())).sort((a:any,b:any)=>seasonNo(a.title)-seasonNo(b.title));
  const currentSeason=seasonNo(m.title), episodes=Math.max(0,Number(m.episode_count)||0), playlist=String(m.full_video_embed_url||''), canIndex=episodes>0&&/videoseries\?list=/i.test(playlist);
  const section=document.createElement('section');section.className='series-browser';
  section.innerHTML=`<div class='series-browser-head'><div><small>EPISODES</small><h2>${esc(base)}</h2></div><span class='episode-count'>${episodes?`${episodes} episodes`:'Series'}</span></div>${seasonRows.length?`<div class='season-tabs'>${seasonRows.map((s:any)=>`<a class='season-tab ${s.slug===m.slug?'active':''}' href='./movie.html?slug=${encodeURIComponent(s.slug)}'>Season ${seasonNo(s.title)}</a>`).join('')}</div>`:''}${canIndex?`<div class='episode-list'>${Array.from({length:episodes},(_,i)=>`<button class='episode-btn ${i===0?'active':''}' data-episode='${i}' type='button'><span class='episode-number'>${i+1}</span><span class='episode-main'><strong>Episode ${i+1}</strong><span>Season ${currentSeason} • Official playlist episode</span></span><span class='episode-play'>▶</span></button>`).join('')}</div><p class='episode-note'>Select an episode to play it in the official CineDesi player above.</p>`:`<p class='muted'>Episode list will appear when episode-level playback is available.</p>`}`;
  const playerSection=document.querySelector('.legal-player-section');if(playerSection)playerSection.insertAdjacentElement('afterend',section);else root.appendChild(section);
  if(canIndex){const iframe=document.querySelector<HTMLIFrameElement>('.legal-player iframe');section.querySelectorAll<HTMLButtonElement>('[data-episode]').forEach(btn=>btn.addEventListener('click',()=>{const idx=Number(btn.dataset.episode||0);section.querySelectorAll('.episode-btn').forEach(x=>x.classList.remove('active'));btn.classList.add('active');if(iframe){iframe.src=`${playlist}&index=${idx}`;document.querySelector('#watch')?.scrollIntoView({behavior:'smooth',block:'start'});}}));}
}
boot();
